In [2]:
import pandas as pd

In [102]:
import numpy as np

In [4]:
pd.__version__

'3.0.5'

In [6]:
DATA = pd.read_csv("car_fuel_efficiency_2026.csv")

In [21]:
DATA.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
DATA.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [8]:
DATA.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [12]:
DATA['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [10]:
DATA.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [13]:
pd.isna(DATA)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False

In [19]:
DATA.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [20]:
DATA.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [37]:
DATA.loc[:,['origin','fuel_efficiency_mpg']].loc[lambda DATA: DATA['origin'] == 'Asia', :].max()

origin                 Asia
fuel_efficiency_mpg    41.2
dtype: object

In [85]:
horsepower_median = DATA.loc[:,'horsepower'].median()

In [83]:
DATA.loc[:,"horsepower"].unique()

array([243., 272., 267., 258., 304., 266., 250., 279., 251., 280.,  nan,
       277., 202., 226., 234., 299., 264., 260., 291., 246., 302., 249.,
       254., 265., 216., 294., 240., 255., 273., 270., 262., 296., 239.,
       248., 282., 238., 231., 289., 232., 321., 235., 257., 284., 233.,
       198., 221., 290., 219., 263., 256., 210., 252., 261., 268., 283.,
       237., 298., 278., 229., 241., 244., 245., 228., 269., 247., 236.,
       259., 200., 224., 275., 271., 285., 242., 295., 213., 253., 297.,
       220., 230., 287., 274., 214., 313., 288., 225., 305., 186., 212.,
       318., 218., 286., 276., 281., 211., 306., 222., 217., 227., 207.,
       308., 209., 181., 197., 205., 309., 206., 208., 201., 204., 223.,
       310., 215., 300., 293., 292., 195., 307., 203., 187., 317., 194.,
       301., 328., 312., 327., 329., 199., 324., 326., 191., 311., 334.,
       188., 190., 303., 319., 314., 325., 316., 182., 171., 332., 315.,
       196., 174., 193., 184., 322., 192., 330., 323., 175., 178., 320.])

In [84]:
horsepower_mode = DATA.loc[:,"horsepower"].mode()[0]

In [86]:
horsepower_median

np.float64(254.0)

In [60]:
DATA.loc[:,'horsepower'].describe()

count    9123.000000
mean      254.446016
std        22.844613
min       171.000000
25%       239.000000
50%       254.000000
75%       270.000000
max       334.000000
Name: horsepower, dtype: float64

In [61]:
DATA_COPY = DATA.copy()

In [75]:
DATA_COPY[['horsepower']] = DATA_COPY[['horsepower']].fillna(horsepower_median)

In [76]:
DATA_COPY.loc[:,'horsepower'].unique()

array([243., 272., 267., 258., 304., 266., 250., 279., 251., 280., 254.,
       277., 202., 226., 234., 299., 264., 260., 291., 246., 302., 249.,
       265., 216., 294., 240., 255., 273., 270., 262., 296., 239., 248.,
       282., 238., 231., 289., 232., 321., 235., 257., 284., 233., 198.,
       221., 290., 219., 263., 256., 210., 252., 261., 268., 283., 237.,
       298., 278., 229., 241., 244., 245., 228., 269., 247., 236., 259.,
       200., 224., 275., 271., 285., 242., 295., 213., 253., 297., 220.,
       230., 287., 274., 214., 313., 288., 225., 305., 186., 212., 318.,
       218., 286., 276., 281., 211., 306., 222., 217., 227., 207., 308.,
       209., 181., 197., 205., 309., 206., 208., 201., 204., 223., 310.,
       215., 300., 293., 292., 195., 307., 203., 187., 317., 194., 301.,
       328., 312., 327., 329., 199., 324., 326., 191., 311., 334., 188.,
       190., 303., 319., 314., 325., 316., 182., 171., 332., 315., 196.,
       174., 193., 184., 322., 192., 330., 323., 175., 178., 320.])

In [79]:
DATA_COPY.loc[:,'horsepower'].median()

np.float64(254.0)

In [87]:
DATA_COPY.loc[:,'horsepower'].mode()[0]

np.float64(254.0)

In [82]:
horsepower_median

np.float64(254.0)

In [88]:
ASIA_CARS = DATA.loc[lambda DATA: DATA['origin'] == 'Asia', :]

In [92]:
ASIA_CARS.loc[:,'origin'].unique()

<StringArray>
['Asia']
Length: 1, dtype: str

In [133]:
ASIA_CARS

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [98]:
X = ASIA_CARS[['vehicle_weight' , 'model_year']].iloc[0:7,:]

In [103]:
x = X.to_numpy()

In [100]:
X

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [134]:
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [135]:
x_transposed = x.transpose()

In [136]:
x_transposed == x.T

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [120]:
M = np.linalg.matmul(x_transposed,x)

In [137]:
xtx = x_transposed.dot(x)

In [138]:
xtx

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [142]:
xtx_inv = np.linalg.inv(xtx)

In [145]:
A = xtx_inv.dot(x_transposed)

In [147]:
A.shape

(2, 7)

In [148]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [150]:
α = A.dot(y)

In [153]:
α.sum().round(3)

np.float64(0.369)